### ISSUE TITLE
Session is not tied by lifetime to the environment => easy segfaults

### ISSUE THREAD

**Issue by aldanor** [nbigaouette/onnxruntime-rs#42] opened 2020-11-29 00:18 UTC
The crate is meant to be safe, but here's one super easy way to segfault it.

Instead of writing

```rust
let environment = Environment::builder()
    .build()?;
let mut session = environment
    .new_session_builder()?
    .with_model_from_file("squeezenet1.0-8.onnx")?;
// session.run()
```

write this

```rust
let mut session = Environment::builder()
    .build()?
    .new_session_builder()?
    .with_model_from_file("squeezenet1.0-8.onnx")?;
// session.run() <--- segfault
```

It's not immediately unclear that you're doing something evil here in the safe code, and it compiles just fine - and then segfaults.

**Comment by nbigaouette** [comment] 2020-11-29 02:00
Thanks for reporting!

I can confirm this issue on 32e9935a8b30cffda3a92f458fb7f2db.

It's weird because `Environment::new_session_builder()` will clone `self` to pass to the new session:
https://github.com/nbigaouette/onnxruntime-rs/blob/32e9935a8b30cffda3a92f458fb7f2db/onnxruntime/src/environment.rs#L138

An environment is a wrapper over the singleton:
https://github.com/nbigaouette/onnxruntime-rs/blob/32e9935a8b30cffda3a92f458fb7f2db/onnxruntime/src/environment.rs#L61-L63

This was done to have a [single environment per process](https://github.com/nbigaouette/onnxruntime-rs/blob/32e9935a8b30cffda3a92f458fb7f2db/onnxruntime/src/environment.rs#L37-L38). This was done because the environment was _not_ (completely) threadsafe: having a logging manager would break the safety. See #18. Since the PR was merged an released, I could revisit how environment and sessions are created, fixing #38 at the same time...

**Closed** 2020-12-27 03:44 UTC
Labels: bug
